# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lingvo/core/ops/hyps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lingvo/core/ops/hyps.proto',
  package='tensorflow.lingvo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1alingvo/core/ops/hyps.proto\x12\x11tensorflow.lingvo\"\xaa\x01\n\nHypothesis\x12\x0f\n\x07\x62\x65\x61m_id\x18\x01 \x01(\x05\x12\x0b\n\x03ids\x18\x02 \x03(\x05\x12\x0e\n\x06scores\x18\x03 \x03(\x02\x12:\n\natten_vecs\x18\x04 \x03(\x0b\x32&.tensorflow.lingvo.Hypothesis.AttenVec\x12\x18\n\x10normalized_score\x18\x05 \x01(\x02\x1a\x18\n\x08\x41ttenVec\x12\x0c\n\x04prob\x18\x01 \x03(\x02')
)




_HYPOTHESIS_ATTENVEC = _descriptor.Descriptor(
  name='AttenVec',
  full_name='tensorflow.lingvo.Hypothesis.AttenVec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prob', full_name='tensorflow.lingvo.Hypothesis.AttenVec.prob', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=220,
)

_HYPOTHESIS = _descriptor.Descriptor(
  name='Hypothesis',
  full_name='tensorflow.lingvo.Hypothesis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beam_id', full_name='tensorflow.lingvo.Hypothesis.beam_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ids', full_name='tensorflow.lingvo.Hypothesis.ids', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scores', full_name='tensorflow.lingvo.Hypothesis.scores', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='atten_vecs', full_name='tensorflow.lingvo.Hypothesis.atten_vecs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalized_score', full_name='tensorflow.lingvo.Hypothesis.normalized_score', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HYPOTHESIS_ATTENVEC, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=220,
)

_HYPOTHESIS_ATTENVEC.containing_type = _HYPOTHESIS
_HYPOTHESIS.fields_by_name['atten_vecs'].message_type = _HYPOTHESIS_ATTENVEC
DESCRIPTOR.message_types_by_name['Hypothesis'] = _HYPOTHESIS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hypothesis = _reflection.GeneratedProtocolMessageType('Hypothesis', (_message.Message,), {

  'AttenVec' : _reflection.GeneratedProtocolMessageType('AttenVec', (_message.Message,), {
    'DESCRIPTOR' : _HYPOTHESIS_ATTENVEC,
    '__module__' : 'lingvo.core.ops.hyps_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.lingvo.Hypothesis.AttenVec)
    })
  ,
  'DESCRIPTOR' : _HYPOTHESIS,
  '__module__' : 'lingvo.core.ops.hyps_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.Hypothesis)
  })
_sym_db.RegisterMessage(Hypothesis)
_sym_db.RegisterMessage(Hypothesis.AttenVec)


# @@protoc_insertion_point(module_scope)
