# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lingvo/core/ops/versioned_file_set.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lingvo/core/ops/versioned_file_set.proto',
  package='tensorflow.lingvo',
  syntax='proto2',
  serialized_options=_b('\370\001\001'),
  serialized_pb=_b('\n(lingvo/core/ops/versioned_file_set.proto\x12\x11tensorflow.lingvo\"l\n\x10VersionedFileSet\x12+\n\x07\x63urrent\x18\x01 \x01(\x0b\x32\x1a.tensorflow.lingvo.FileSet\x12+\n\x07history\x18\x02 \x03(\x0b\x32\x1a.tensorflow.lingvo.FileSet\"9\n\x07\x46ileSet\x12\x14\n\x0c\x66ile_pattern\x18\x01 \x03(\t\x12\x18\n\x10\x63reate_timestamp\x18\x02 \x01(\x01\x42\x03\xf8\x01\x01')
)




_VERSIONEDFILESET = _descriptor.Descriptor(
  name='VersionedFileSet',
  full_name='tensorflow.lingvo.VersionedFileSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current', full_name='tensorflow.lingvo.VersionedFileSet.current', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='history', full_name='tensorflow.lingvo.VersionedFileSet.history', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=171,
)


_FILESET = _descriptor.Descriptor(
  name='FileSet',
  full_name='tensorflow.lingvo.FileSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_pattern', full_name='tensorflow.lingvo.FileSet.file_pattern', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_timestamp', full_name='tensorflow.lingvo.FileSet.create_timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=230,
)

_VERSIONEDFILESET.fields_by_name['current'].message_type = _FILESET
_VERSIONEDFILESET.fields_by_name['history'].message_type = _FILESET
DESCRIPTOR.message_types_by_name['VersionedFileSet'] = _VERSIONEDFILESET
DESCRIPTOR.message_types_by_name['FileSet'] = _FILESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionedFileSet = _reflection.GeneratedProtocolMessageType('VersionedFileSet', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONEDFILESET,
  '__module__' : 'lingvo.core.ops.versioned_file_set_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.VersionedFileSet)
  })
_sym_db.RegisterMessage(VersionedFileSet)

FileSet = _reflection.GeneratedProtocolMessageType('FileSet', (_message.Message,), {
  'DESCRIPTOR' : _FILESET,
  '__module__' : 'lingvo.core.ops.versioned_file_set_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.FileSet)
  })
_sym_db.RegisterMessage(FileSet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
