# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lingvo/core/hyperparams.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lingvo/core/hyperparams.proto',
  package='tensorflow.lingvo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1dlingvo/core/hyperparams.proto\x12\x11tensorflow.lingvo\"\x97\x01\n\nHyperparam\x12\x37\n\x05items\x18\x01 \x03(\x0b\x32(.tensorflow.lingvo.Hyperparam.ItemsEntry\x1aP\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".tensorflow.lingvo.HyperparamValue:\x02\x38\x01\"G\n\x12HyperparamRepeated\x12\x31\n\x05items\x18\x01 \x03(\x0b\x32\".tensorflow.lingvo.HyperparamValue\"\x91\x04\n\x0fHyperparamValue\x12\x32\n\tparam_val\x18\x01 \x01(\x0b\x32\x1d.tensorflow.lingvo.HyperparamH\x00\x12\x39\n\x08list_val\x18\x02 \x01(\x0b\x32%.tensorflow.lingvo.HyperparamRepeatedH\x00\x12:\n\ttuple_val\x18\x03 \x01(\x0b\x32%.tensorflow.lingvo.HyperparamRepeatedH\x00\x12\x31\n\x08\x64ict_val\x18\x04 \x01(\x0b\x32\x1d.tensorflow.lingvo.HyperparamH\x00\x12\x12\n\x08type_val\x18\x05 \x01(\tH\x00\x12\x13\n\tdtype_val\x18\x06 \x01(\tH\x00\x12\x14\n\nstring_val\x18\x07 \x01(\tH\x00\x12\x12\n\x08\x62ool_val\x18\x08 \x01(\x08H\x00\x12\x11\n\x07int_val\x18\t \x01(\x03H\x00\x12\x13\n\tfloat_val\x18\n \x01(\x02H\x00\x12\x30\n\tproto_val\x18\x0b \x01(\x0b\x32\x1b.tensorflow.lingvo.ProtoValH\x00\x12.\n\x08\x65num_val\x18\x0c \x01(\x0b\x32\x1a.tensorflow.lingvo.EnumValH\x00\x12;\n\x0fnamed_tuple_val\x18\r \x01(\x0b\x32 .tensorflow.lingvo.NamedTupleValH\x00\x42\x06\n\x04kind\"%\n\x08ProtoVal\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\x0c\"%\n\x07\x45numVal\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"P\n\rNamedTupleVal\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x31\n\x05items\x18\x02 \x03(\x0b\x32\".tensorflow.lingvo.HyperparamValue')
)




_HYPERPARAM_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='tensorflow.lingvo.Hyperparam.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tensorflow.lingvo.Hyperparam.ItemsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='tensorflow.lingvo.Hyperparam.ItemsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=204,
)

_HYPERPARAM = _descriptor.Descriptor(
  name='Hyperparam',
  full_name='tensorflow.lingvo.Hyperparam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='tensorflow.lingvo.Hyperparam.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HYPERPARAM_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=204,
)


_HYPERPARAMREPEATED = _descriptor.Descriptor(
  name='HyperparamRepeated',
  full_name='tensorflow.lingvo.HyperparamRepeated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='tensorflow.lingvo.HyperparamRepeated.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=277,
)


_HYPERPARAMVALUE = _descriptor.Descriptor(
  name='HyperparamValue',
  full_name='tensorflow.lingvo.HyperparamValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param_val', full_name='tensorflow.lingvo.HyperparamValue.param_val', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list_val', full_name='tensorflow.lingvo.HyperparamValue.list_val', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tuple_val', full_name='tensorflow.lingvo.HyperparamValue.tuple_val', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dict_val', full_name='tensorflow.lingvo.HyperparamValue.dict_val', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_val', full_name='tensorflow.lingvo.HyperparamValue.type_val', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype_val', full_name='tensorflow.lingvo.HyperparamValue.dtype_val', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_val', full_name='tensorflow.lingvo.HyperparamValue.string_val', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_val', full_name='tensorflow.lingvo.HyperparamValue.bool_val', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_val', full_name='tensorflow.lingvo.HyperparamValue.int_val', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_val', full_name='tensorflow.lingvo.HyperparamValue.float_val', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proto_val', full_name='tensorflow.lingvo.HyperparamValue.proto_val', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum_val', full_name='tensorflow.lingvo.HyperparamValue.enum_val', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='named_tuple_val', full_name='tensorflow.lingvo.HyperparamValue.named_tuple_val', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='tensorflow.lingvo.HyperparamValue.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=280,
  serialized_end=809,
)


_PROTOVAL = _descriptor.Descriptor(
  name='ProtoVal',
  full_name='tensorflow.lingvo.ProtoVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tensorflow.lingvo.ProtoVal.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='tensorflow.lingvo.ProtoVal.val', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=811,
  serialized_end=848,
)


_ENUMVAL = _descriptor.Descriptor(
  name='EnumVal',
  full_name='tensorflow.lingvo.EnumVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tensorflow.lingvo.EnumVal.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='tensorflow.lingvo.EnumVal.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=850,
  serialized_end=887,
)


_NAMEDTUPLEVAL = _descriptor.Descriptor(
  name='NamedTupleVal',
  full_name='tensorflow.lingvo.NamedTupleVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tensorflow.lingvo.NamedTupleVal.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='tensorflow.lingvo.NamedTupleVal.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=889,
  serialized_end=969,
)

_HYPERPARAM_ITEMSENTRY.fields_by_name['value'].message_type = _HYPERPARAMVALUE
_HYPERPARAM_ITEMSENTRY.containing_type = _HYPERPARAM
_HYPERPARAM.fields_by_name['items'].message_type = _HYPERPARAM_ITEMSENTRY
_HYPERPARAMREPEATED.fields_by_name['items'].message_type = _HYPERPARAMVALUE
_HYPERPARAMVALUE.fields_by_name['param_val'].message_type = _HYPERPARAM
_HYPERPARAMVALUE.fields_by_name['list_val'].message_type = _HYPERPARAMREPEATED
_HYPERPARAMVALUE.fields_by_name['tuple_val'].message_type = _HYPERPARAMREPEATED
_HYPERPARAMVALUE.fields_by_name['dict_val'].message_type = _HYPERPARAM
_HYPERPARAMVALUE.fields_by_name['proto_val'].message_type = _PROTOVAL
_HYPERPARAMVALUE.fields_by_name['enum_val'].message_type = _ENUMVAL
_HYPERPARAMVALUE.fields_by_name['named_tuple_val'].message_type = _NAMEDTUPLEVAL
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['param_val'])
_HYPERPARAMVALUE.fields_by_name['param_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['list_val'])
_HYPERPARAMVALUE.fields_by_name['list_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['tuple_val'])
_HYPERPARAMVALUE.fields_by_name['tuple_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['dict_val'])
_HYPERPARAMVALUE.fields_by_name['dict_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['type_val'])
_HYPERPARAMVALUE.fields_by_name['type_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['dtype_val'])
_HYPERPARAMVALUE.fields_by_name['dtype_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['string_val'])
_HYPERPARAMVALUE.fields_by_name['string_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['bool_val'])
_HYPERPARAMVALUE.fields_by_name['bool_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['int_val'])
_HYPERPARAMVALUE.fields_by_name['int_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['float_val'])
_HYPERPARAMVALUE.fields_by_name['float_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['proto_val'])
_HYPERPARAMVALUE.fields_by_name['proto_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['enum_val'])
_HYPERPARAMVALUE.fields_by_name['enum_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_HYPERPARAMVALUE.oneofs_by_name['kind'].fields.append(
  _HYPERPARAMVALUE.fields_by_name['named_tuple_val'])
_HYPERPARAMVALUE.fields_by_name['named_tuple_val'].containing_oneof = _HYPERPARAMVALUE.oneofs_by_name['kind']
_NAMEDTUPLEVAL.fields_by_name['items'].message_type = _HYPERPARAMVALUE
DESCRIPTOR.message_types_by_name['Hyperparam'] = _HYPERPARAM
DESCRIPTOR.message_types_by_name['HyperparamRepeated'] = _HYPERPARAMREPEATED
DESCRIPTOR.message_types_by_name['HyperparamValue'] = _HYPERPARAMVALUE
DESCRIPTOR.message_types_by_name['ProtoVal'] = _PROTOVAL
DESCRIPTOR.message_types_by_name['EnumVal'] = _ENUMVAL
DESCRIPTOR.message_types_by_name['NamedTupleVal'] = _NAMEDTUPLEVAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hyperparam = _reflection.GeneratedProtocolMessageType('Hyperparam', (_message.Message,), {

  'ItemsEntry' : _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), {
    'DESCRIPTOR' : _HYPERPARAM_ITEMSENTRY,
    '__module__' : 'lingvo.core.hyperparams_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.lingvo.Hyperparam.ItemsEntry)
    })
  ,
  'DESCRIPTOR' : _HYPERPARAM,
  '__module__' : 'lingvo.core.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.Hyperparam)
  })
_sym_db.RegisterMessage(Hyperparam)
_sym_db.RegisterMessage(Hyperparam.ItemsEntry)

HyperparamRepeated = _reflection.GeneratedProtocolMessageType('HyperparamRepeated', (_message.Message,), {
  'DESCRIPTOR' : _HYPERPARAMREPEATED,
  '__module__' : 'lingvo.core.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.HyperparamRepeated)
  })
_sym_db.RegisterMessage(HyperparamRepeated)

HyperparamValue = _reflection.GeneratedProtocolMessageType('HyperparamValue', (_message.Message,), {
  'DESCRIPTOR' : _HYPERPARAMVALUE,
  '__module__' : 'lingvo.core.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.HyperparamValue)
  })
_sym_db.RegisterMessage(HyperparamValue)

ProtoVal = _reflection.GeneratedProtocolMessageType('ProtoVal', (_message.Message,), {
  'DESCRIPTOR' : _PROTOVAL,
  '__module__' : 'lingvo.core.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.ProtoVal)
  })
_sym_db.RegisterMessage(ProtoVal)

EnumVal = _reflection.GeneratedProtocolMessageType('EnumVal', (_message.Message,), {
  'DESCRIPTOR' : _ENUMVAL,
  '__module__' : 'lingvo.core.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.EnumVal)
  })
_sym_db.RegisterMessage(EnumVal)

NamedTupleVal = _reflection.GeneratedProtocolMessageType('NamedTupleVal', (_message.Message,), {
  'DESCRIPTOR' : _NAMEDTUPLEVAL,
  '__module__' : 'lingvo.core.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.NamedTupleVal)
  })
_sym_db.RegisterMessage(NamedTupleVal)


_HYPERPARAM_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
