# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lingvo/tasks/mt/text_input.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lingvo/tasks/mt/text_input.proto',
  package='tensorflow.lingvo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n lingvo/tasks/mt/text_input.proto\x12\x11tensorflow.lingvo\"*\n\x08Sentence\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\"t\n\x0cSentencePair\x12\x31\n\x0csrc_sentence\x18\x01 \x01(\x0b\x32\x1b.tensorflow.lingvo.Sentence\x12\x31\n\x0ctgt_sentence\x18\x02 \x01(\x0b\x32\x1b.tensorflow.lingvo.Sentence')
)




_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='tensorflow.lingvo.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='tensorflow.lingvo.Sentence.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='tensorflow.lingvo.Sentence.lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=97,
)


_SENTENCEPAIR = _descriptor.Descriptor(
  name='SentencePair',
  full_name='tensorflow.lingvo.SentencePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_sentence', full_name='tensorflow.lingvo.SentencePair.src_sentence', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tgt_sentence', full_name='tensorflow.lingvo.SentencePair.tgt_sentence', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=215,
)

_SENTENCEPAIR.fields_by_name['src_sentence'].message_type = _SENTENCE
_SENTENCEPAIR.fields_by_name['tgt_sentence'].message_type = _SENTENCE
DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
DESCRIPTOR.message_types_by_name['SentencePair'] = _SENTENCEPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), {
  'DESCRIPTOR' : _SENTENCE,
  '__module__' : 'lingvo.tasks.mt.text_input_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.Sentence)
  })
_sym_db.RegisterMessage(Sentence)

SentencePair = _reflection.GeneratedProtocolMessageType('SentencePair', (_message.Message,), {
  'DESCRIPTOR' : _SENTENCEPAIR,
  '__module__' : 'lingvo.tasks.mt.text_input_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.lingvo.SentencePair)
  })
_sym_db.RegisterMessage(SentencePair)


# @@protoc_insertion_point(module_scope)
